from . import res_partner
from . import account_move
from . import product_template
from . import sale_order
from . import account_invoice_report
from . import stock_picking_fictitious
from . import stock_picking
from . import account_payment
from . import account_payment_register
from . import account_journal
from . import stock_picking_type